---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Pratik Bhikadiya"
date: "11/09/2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:
```{r}
install.packages("Lahman")
```

```{r load-pkg-data}
#| message: false
library(Lahman)
```

## Exercises

### Exercise 1

```{r}
install.packages("tidyverse")
library(tidyverse)

```


```{r glimpse-data}
library(Lahman)
dim(Teams)
dplyr::glimpse(Teams)

```

The `Teams` dataset has 3015 observations and 48 variables.

### Exercise 2
```{r Ben Baumer worked for the New York Mets from 2004 to 2012}
view(Teams)
```
```{r}
mets <- Teams  %>% 
  dplyr::filter(teamID == "NYN")
my_mets <- mets %>% 
  dplyr::filter(yearID >=2004 & yearID <=2012)
my_mets %>% 
  dplyr::select(yearID,W,L,teamID)
```

...

### Exercise 3
```{r}
mets_ben <- Teams %>%
  dplyr::select(yearID, teamID, R, RA, W, L) %>%
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)

```
```{r}
view(mets_ben)
```

```{r}
mets_ben <- mets_ben |>
  dplyr::rename(RS= R)    # new name = old name
mets_ben
```


### Exercise 4

```{r}
install.packages("dplyr")


```
```{r}

library(dplyr)

```

```{r}
install.packages("magrittr")


```

```{r}
library(magrittr)
```


```{r}
mets_ben <- mets_ben %>%
  dplyr::mutate(WPct = 1 / (1 + (RA / RS) * 2))

```

```{r}
View(mets_ben)
```


```{r}
mets_ben <- mets_ben %>%
  dplyr::mutate(W_hat = WPct * (W ))
```

...




### Exercise 5




```{r}

# Add a column to identify whether the Mets performed better or worse than expected
mets_ben <- mets_ben %>%
 dplyr:: mutate(Performance = ifelse(W > W_hat, "Better", "Worse"))

mets_ben

```


```{r}
library(dplyr)

summary_stats <- mets_ben %>%
  group_by(Performance) %>%
  summarize(count = n())

print(summary_stats)

```

### Exercise 6


```{r}
best_seasons <- dplyr::arrange(mets_ben, desc(W))

best_seasons

```


...

### Exercise 7

```{r}
mets_ben <-mets_ben %>% 
  dplyr::mutate(Diff = W -W_hat) |>
  dplyr::arrange(desc(Diff))


```

```{r}
View(mets_ben)
```

...

### Exercise 8

```{r}
mets_ben |>
  dplyr::summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct =mean(WPct), 
    sum_resid = sum(Diff)
  )
```

...

### Exercise 9
```{r}

```

...

### Exercise 10


```{r}

```


```{r}

library(dplyr)
mets_ben <- mets_ben %>%
  dplyr::mutate(
    gm = case_when(
      yearID == 2004 ~ "Jim Duquette",
      yearID >= 2005 & yearID <= 2010 ~ "Omar Minaya",
      yearID >= 2011 ~ "Sandy Alderson"
    )
  )





```
```{r}
mets_ben
```


...
# Excercise 11

```{r Group by the manager (gm) variable and summarize the data}
 
manager_summary <- mets_ben %>%
  group_by(gm) %>%
  summarize(
    num_years = n(),
    total_W = sum(W),
    total_L = sum(L),
    total_WPct = mean(WPct),
    sum_resid = sum(Diff)
  )

# Print the manager summary
manager_summary


```

